version: '3.9'
services:
  
  kaggle:
    image: gcr.io/kaggle-images/python
    working_dir: /kaggle/working
    volumes:
      - ./Python:/home/jupyter
      - ./Kaggle:/kaggle
      - ./Python/tic-tac-toe.ipynb:/kaggle/working/tic-tac-toe.ipynb:rw
      - ./VsCodeConfigFolders/kaggle:/home/jupyter/.vscode-server
    ports:
      - 8080:8080
      - 8880:8888
    
  jupyter:
    image: jupyter/datascience-notebook:r-4.0.3
    # environment:
    #  - JUPYTER TOKEN=ja89osj4rm8pojdl
    volumes:
      - ./Python:/home/jovyan
    ports:
      - 8888:8888
    container_name: jupyter
    # command: jupyter notebook list
    
  python_ai:
    deploy:
      resources:
        limits:
          memory: 450m
    build:
      args:
        python_version: ${PYTHON_VERSION}
      context: .
      dockerfile: Dockerfiles/python.Dockerfile
      target: ${MODE_PYTHON}
    container_name: python_ai
    networks:
      pythonNetAi:
        aliases:
          - python_ai
    expose:
      - 8000
    ports:
      - 8000:8000
    user: worker
    volumes:
      - ./VsCodeConfigFolders/Python:/home/worker/.vscode-server/
      - ./Python/w:/usr/src/app
    
    # restart: always
    working_dir: /usr/src/app   
  
networks:
  pythonNetAi:
    driver: bridge
    name: pythonNetAi
