version: '3.9'
services:     
  python_server:
    build:
      args:
        python_version: ${PYTHON_VERSION}
      context: .
      dockerfile: Dockerfiles/python.Dockerfile
      target: ${MODE_PYTHON_SERVER}
    container_name: python_server
    # command: npm start
    # environment:
    #   REACT_APP_FOR: dEVELOP
    networks:
      pythonNet:
        aliases:
          - python_server
    ports:
      - 3000:3000
    user: worker
    volumes:
      - ./VsCodeConfigFolders/Python:/home/worker/.vscode-server/
      - ./Python/w:/usr/src/app
      # - pythonModules:/usr/src/app
    # restart: always
    
    working_dir: /usr/src/app

networks:
  pythonNet:
    driver: bridge
    name: pythonNet

# volumes:
#   node_modules_api:
