version: '3.9'
services:     
  python:
    build:
      args:
        python_version: ${PYTHON_VERSION}
      context: .
      dockerfile: Dockerfiles/python.Dockerfile
      target: ${MODE_PYTHON}
    container_name: python
    # command: npm start
    # environment:
    #   PYTHONHOME: /opt/venv/bin/
    #   PYTHONPATH: /usr/src/app/
    networks:
      pythonNet:
        aliases:
          - python
    ports:
      - 5678:5678
    user: worker
    volumes:
      - ./VsCodeConfigFolders/Python:/home/worker/.vscode-server/
      - ./Python:/usr/src/app
      - pythonInstall:/usr/local/lib/python3.10/:r
    # restart: always
    working_dir: /usr/src/app

networks:
  pythonNet:
    driver: bridge
    name: pythonNet

volumes:
  pythonInstall:
