# Generated by Django 4.1.1 on 2022-10-26 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_pairtictactoe_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairtictactoe',
            name='game_opponent',
        ),
        migrations.AlterField(
            model_name='pairtictactoe',
            name='room_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_robot', models.BooleanField(default=False)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AlterField(
            model_name='pairtictactoe',
            name='game_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.player'),
        ),
    ]
