# Generated by Django 4.1.1 on 2022-10-26 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_remove_pairtictactoe_game_opponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairtictactoe',
            name='game_opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_opponent', to='polls.player'),
        ),
        migrations.AlterField(
            model_name='pairtictactoe',
            name='game_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_creator', to='polls.player'),
        ),
        migrations.AlterField(
            model_name='pairtictactoe',
            name='room_code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
